### ISSUE TITLE
Hero fixado em rolagem mobile

### ISSUE THREAD

**Issue by joaovitor2763** [CovidZero/covidzero-bot-slack#1]
Quando rolamos a página na versão mobile, o Hero inteiro se mantem fixo atrapalhando a visualização.

![WhatsApp Image 2020-03-21 at 10 29 28](https://user-images.githubusercontent.com/8019800/77227560-ea963880-6b5f-11ea-8987-278d4de97513.jpeg)

**Comment by VictorHaine** [comment]
@joaovitor2763 Fiz um fix hoje, pra carregar dinâmicamente o conteúdo e incluir na página, ao invés de utilizar um iFrame. Veja se resolveu ai pra você também.
